name: ivorypay
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  bip39: ^1.0.6
  chart_sparkline: ^1.0.13
  clock: ^1.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.1
  dio_cache_interceptor_hive_store: ^3.2.1
  ed25519_hd_key: ^2.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  responsive_framework: ^0.2.0
  shimmer: ^2.0.0
  slide_to_act: ^2.0.1
  ternav_icons: ^1.0.0
  web3dart: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/gif/
    - assets/certificates/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLTPro-Bd.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueLTPro-Md.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeueLTPro-Roman.otf
          weight: 400
